# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51e454013f49270ad879db62b4b453643e8815645691935eb9b13de3ec1963851ab9c3d19298cd54220702413bc4b3559496e89de33f463ff43edba27bf0ee5a

test:
  secret_key_base: a0a7f66f892fe92dd44ee79da75c99134b376db20f76717b0cdd3003e06a0bf2f19777f8f0171f929b8ccd16dd9cc8ffa69753a9ce5cbb9c595d710ce7451f40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
